package aaTesterOnlyCode;

import java.util.Arrays;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;

public class Top500WebSitesParser {
	
	public static void main(String[] args) {
		
//		try {
//			Document doc = Jsoup.connect("https://moz.com/top500").get();
//			Elements elements = doc.getElementsByClass("url");
//			ArrayList<String> urls = new ArrayList<>();
//			int[] counter = { 0 };
//			elements.forEach(td -> {
//				Elements a = td.getElementsByTag("a");
//				//System.out.println( ( ++counter[0] ) + " -> " + a.get(0).attr("href"));
//				System.out.println("\""+a.get(0).attr("href")+"\",");
//				urls.add("\""+a.get(0).attr("href")+"\"");
//			});
//			
//		//	String string = urls.toString();
//			//System.out.println(string);
//		} catch (IOException e) {
//			e.printStackTrace();
//		}
		
		
//		//Parse Alex_data csv
//		 try (BufferedReader br = new BufferedReader(new FileReader("alexa_data.csv"))) {
//
//			 br.lines().forEach(line->{
//				 System.out.println("\""+"http://www."+line.split(",")[1].replaceAll("\"", "")+"\",");
//			 });
//
//	        } catch (IOException e) {
//	            e.printStackTrace();
//	        }
		
		 
		 //Remove duplicates from the List
		for(int i=0; i<websites.size(); i++) {
			websites.set(i,"\""+ websites.get(i).replaceAll("https", "http").replaceAll("http", "https").replaceAll("www\\.", "").replaceAll("\\/\\/", "\\/\\/www.")+"\",");
		}
			

		SortedSet<String> tree = new TreeSet<>(websites);
		tree.forEach(System.out::println);
		System.out.println(tree.size());
				
	}
	
	private static List<String> websites = Arrays.asList("https://www.fb.com", "http://facebook.com", "http://twitter.com", "http://google.com",
			"http://youtube.com", "http://linkedin.com", "http://wordpress.org", "http://instagram.com", "http://pinterest.com", "http://wikipedia.org", "http://wordpress.com",
			"http://blogspot.com", "http://apple.com", "http://adobe.com", "http://tumblr.com", "http://youtu.be", "http://amazon.com", "http://vimeo.com", "http://goo.gl",
			"http://godaddy.com", "http://yahoo.com", "http://microsoft.com", "http://flickr.com", "http://bit.ly", "http://qq.com", "http://buydomains.com",
			"http://whoisprivacyprotect.com", "http://w3.org", "http://vk.com", "http://nytimes.com", "http://reddit.com", "http://baidu.com", "http://t.co", "http://europa.eu",
			"http://ascii.co.uk", "http://bbc.co.uk", "http://statcounter.com", "http://weebly.com", "http://myspace.com", "http://gov.uk", "http://yandex.ru",
			"http://soundcloud.com", "http://blogger.com", "http://mozilla.org", "http://google.de", "http://github.com", "http://bluehost.com", "http://cnn.com", "http://wix.com",
			"http://addthis.com", "http://parallels.com", "http://creativecommons.org", "http://huffingtonpost.com", "http://issuu.com", "http://miitbeian.gov.cn",
			"http://feedburner.com", "http://nih.gov", "http://go.com", "http://imdb.com", "http://theguardian.com", "http://digg.com", "http://stumbleupon.com",
			"http://forbes.com", "http://google.co.jp", "http://123-reg.co.uk", "http://paypal.com", "http://tinyurl.com", "http://wsj.com", "http://wp.com", "http://jimdo.com",
			"http://msn.com", "http://dropbox.com", "http://miibeian.gov.cn", "http://wixsite.com", "http://washingtonpost.com", "http://slideshare.net", "http://amazonaws.com",
			"http://yelp.com", "http://weibo.com", "http://google.co.uk", "http://eventbrite.com", "http://telegraph.co.uk", "http://archive.org", "http://etsy.com",
			"http://addtoany.com", "http://reuters.com", "http://typepad.com", "http://sourceforge.net", "http://free.fr", "http://domainmarket.com", "http://livejournal.com",
			"http://bloomberg.com", "http://about.com", "http://ebay.com", "http://dailymail.co.uk", "http://aol.com", "http://bing.com", "http://mail.ru", "http://sina.com.cn",
			"http://usatoday.com", "http://ameblo.jp", "http://fc2.com", "http://amazon.co.uk", "http://51.la", "http://time.com", "http://secureserver.net",
			"http://macromedia.com", "http://e-recht24.de", "http://taobao.com", "http://domainactive.co", "http://wikimedia.org", "http://constantcontact.com",
			"http://gravatar.com", "http://yahoo.co.jp", "http://eepurl.com", "http://amazon.de", "http://harvard.edu", "http://latimes.com", "http://npr.org", "http://cdc.gov",
			"http://guardian.co.uk", "http://xing.com", "http://surveymonkey.com", "http://live.com", "http://dailymotion.com", "http://webs.com", "http://namejet.com",
			"http://mit.edu", "http://blogspot.co.uk", "http://amzn.to", "http://list-manage.com", "http://stanford.edu", "http://wired.com", "http://bbb.org", "http://icio.us",
			"http://opera.com", "http://apache.org", "http://tripadvisor.com", "http://businessinsider.com", "http://rambler.ru", "http://hostnet.nl", "http://nasa.gov",
			"http://kickstarter.com", "http://independent.co.uk", "http://cnet.com", "http://cpanel.net", "http://hatena.ne.jp", "http://bandcamp.com", "http://bbc.com",
			"http://gnu.org", "http://geocities.com", "http://cpanel.com", "http://scribd.com", "http://amazon.co.jp", "http://joomla.org", "http://elegantthemes.com",
			"http://ted.com", "http://163.com", "http://imgur.com", "http://photobucket.com", "http://google.it", "http://behance.net", "http://tripod.com",
			"http://directdomains.com", "http://delicious.com", "http://medium.com", "http://1und1.de", "http://google.fr", "http://googleusercontent.com", "http://deviantart.com",
			"http://un.org", "http://disqus.com", "http://trustpilot.com", "http://pbs.org", "http://github.io", "http://ca.gov", "http://who.int", "http://wiley.com",
			"http://nationalgeographic.com", "http://mashable.com", "http://google.es", "http://cbsnews.com", "http://ibm.com", "http://goodreads.com", "http://berkeley.edu",
			"http://google.ca", "http://whitehouse.gov", "http://barnesandnoble.com", "http://homestead.com", "http://detik.com", "http://nbcnews.com", "http://spotify.com",
			"http://foxnews.com", "http://theatlantic.com", "http://one.com", "http://rakuten.co.jp", "http://nature.com", "http://buzzfeed.com", "http://techcrunch.com",
			"http://plesk.com", "http://cornell.edu", "http://beian.gov.cn", "http://usda.gov", "http://squarespace.com", "http://sciencedirect.com", "http://loopia.se",
			"http://mijndomein.nl", "http://change.org", "http://ft.com", "http://vkontakte.ru", "http://blogspot.com.es", "http://visma.com", "http://loopia.com", "http://cbc.ca",
			"http://doubleclick.net", "http://sakura.ne.jp", "http://epa.gov", "http://noaa.gov", "http://blogspot.ca", "http://ow.ly", "http://php.net", "http://blogspot.de",
			"http://webmd.com", "http://economist.com", "http://loc.gov", "http://springer.com", "http://meetup.com", "http://sfgate.com", "http://spiegel.de", "http://4.cn",
			"http://technorati.com", "http://nps.gov", "http://themeforest.net", "http://networksolutions.com", "http://bizjournals.com", "http://usnews.com", "http://ning.com",
			"http://cbslocal.com", "http://wikia.com", "http://engadget.com", "http://prnewswire.com", "http://chicagotribune.com", "http://wp.me", "http://xinhuanet.com",
			"http://newyorker.com", "http://gizmodo.com", "http://abc.net.au", "http://list-manage1.com", "http://bola.net", "http://slate.com", "http://cnbc.com",
			"http://cloudfront.net", "http://skype.com", "http://jiathis.com", "http://hp.com", "http://about.me", "http://fda.gov", "http://foursquare.com", "http://line.me",
			"http://mapquest.com", "http://nydailynews.com", "http://blogspot.fr", "http://wufoo.com", "http://umich.edu", "http://businessweek.com", "http://acquirethisname.com",
			"http://marriott.com", "http://domainname.de", "http://booking.com", "http://house.gov", "http://state.gov", "http://1and1.fr", "http://unesco.org",
			"http://bigcartel.com", "http://fortune.com", "http://yale.edu", "http://columbia.edu", "http://indiegogo.com", "http://ustream.tv", "http://ed.gov",
			"http://youku.com", "http://irs.gov", "http://storify.com", "http://phpbb.com", "http://sogou.com", "http://sedo.com", "http://rs6.net", "http://geocities.jp",
			"http://google.com.au", "http://examiner.com", "http://google.nl", "http://vice.com", "http://myshopify.com", "http://nifty.com", "http://upenn.edu",
			"http://boston.com", "http://indiatimes.com", "http://naver.com", "http://a8.net", "http://washington.edu", "http://hibu.com", "http://fb.me", "http://hilton.com",
			"http://marketwatch.com", "http://histats.com", "http://home.pl", "http://livedoor.jp", "http://axs.com", "http://doi.org", "http://ocn.ne.jp", "http://weather.com",
			"http://oracle.com", "http://zdnet.com", "http://nhs.uk", "http://afternic.com", "http://smh.com.au", "http://1and1.com", "http://senate.gov", "http://ucla.edu",
			"http://archives.gov", "http://theverge.com", "http://samsung.com", "http://android.com", "http://businesswire.com", "http://fb.com", "http://domainnameshop.com",
			"http://linksynergy.com", "http://uk2.net", "http://phoca.cz", "http://theglobeandmail.com", "http://nypost.com", "http://utexas.edu", "http://umn.edu",
			"http://wunderground.com", "http://umblr.com", "http://wisc.edu", "http://scientificamerican.com", "http://domeneshop.no", "http://fastcompany.com",
			"http://enable-javascript.com", "http://alibaba.com", "http://psu.edu", "http://debian.org", "http://dribbble.com", "http://ap.org", "http://academia.edu",
			"http://ox.ac.uk", "http://thetimes.co.uk", "http://uol.com.br", "http://campaign-archive1.com", "http://sagepub.com", "http://clickbank.net",
			"http://bestfwdservice.com", "http://campaign-archive2.com", "http://nazwa.pl", "http://salon.com", "http://dreamhost.com", "http://mailchimp.com",
			"http://sciencemag.org", "http://si.edu", "http://worldbank.org", "http://ftc.gov", "http://goo.ne.jp", "http://wikihow.com", "http://census.gov", "http://intel.com",
			"http://mozilla.com", "http://gofundme.com", "http://walmart.com", "http://google.com.br", "http://princeton.edu", "http://nymag.com", "http://discovery.com",
			"http://t-online.de", "http://evernote.com", "http://elpais.com", "http://mirror.co.uk", "http://fbcdn.net", "http://drupal.org", "http://houzz.com", "http://usgs.gov",
			"http://mlb.com", "http://hostgator.com", "http://inc.com", "http://networkadvertising.org", "http://cam.ac.uk", "http://rollingstone.com", "http://nyu.edu",
			"http://hbr.org", "http://alexa.com", "http://cisco.com", "http://thedailybeast.com", "http://oxfordjournals.org", "http://arstechnica.com", "http://prweb.com",
			"http://lemonde.fr", "http://newsweek.com", "http://entrepreneur.com", "http://icann.org", "http://xiti.com", "http://politico.com", "http://studiopress.com",
			"http://google.pl", "http://exblog.jp", "http://tandfonline.com", "http://oecd.org", "http://dropboxusercontent.com", "http://cmu.edu", "http://uchicago.edu",
			"http://aboutcookies.org", "http://target.com", "http://odin.com", "http://espn.com", "http://globo.com", "http://hollywoodreporter.com", "http://feedly.com",
			"http://hhs.gov", "http://allaboutcookies.org", "http://lifehacker.com", "http://ok.ru", "http://list-manage2.com", "http://mysql.com", "http://shareasale.com",
			"http://livestream.com", "http://hubspot.com", "http://dell.com", "http://stackoverflow.com", "http://zendesk.com", "http://aljazeera.com", "http://office.com",
			"http://news.com.au", "http://smugmug.com", "http://youronlinechoices.com", "http://web.de", "http://tripadvisor.co.uk", "http://admin.ch", "http://researchgate.net",
			"http://jugem.jp", "http://bls.gov", "http://adweek.com", "http://cafepress.com", "http://usc.edu", "http://variety.com", "http://att.com", "http://duke.edu",
			"http://bmj.com", "http://unc.edu", "http://mtv.com", "http://redcross.org", "http://shinystat.com", "http://nhk.or.jp", "http://today.com", "http://ieee.org",
			"http://example.com", "http://box.com", "http://ewebdevelopment.com", "http://accuweather.com", "http://themegrill.com", "http://com.com", "http://fao.org",
			"http://apa.org", "http://ebay.co.uk", "http://ucsd.edu", "http://telnames.net", "http://liveinternet.ru", "http://seattletimes.com", "http://istockphoto.com",
			"http://army.mil", "http://va.gov", "http://nielsen.com", "http://nsw.gov.au", "http://venturebeat.com", "http://register.it", "http://managemy.tel",
			"http://netflix.com", "http://bostonglobe.com", "http://teamviewer.com", "http://washingtontimes.com", "http://vox.com", "http://pcworld.com", "http://dot.gov",
			"http://symantec.com", "http://warnerbros.com", "http://google.co.in", "http://telegram.me", "http://blogspot.jp", "http://ibtimes.com", "http://bund.de",
			"http://gpo.gov", "http://antaranews.com", "http://shop-pro.jp", "http://dandomain.dk", "http://prezi.com", "http://netscape.com", "http://google.ru",
			"http://eventbrite.co.uk", "http://usa.gov", "http://nginx.org", "http://aliyun.com", "http://windowsphone.com", "http://openstreetmap.org", "http://www.google.com",
			"http://www.youtube.com", "http://www.facebook.com", "http://www.baidu.com", "http://www.wikipedia.org", "http://www.yahoo.com", "http://www.google.co.in",
			"http://www.reddit.com", "http://www.qq.com", "http://www.taobao.com", "http://www.twitter.com", "http://www.amazon.com", "http://www.google.co.jp",
			"http://www.tmall.com", "http://www.vk.com", "http://www.live.com", "http://www.sohu.com", "http://www.instagram.com", "http://www.jd.com", "http://www.sina.com.cn",
			"http://www.weibo.com", "http://www.360.cn", "http://www.google.de", "http://www.google.co.uk", "http://www.linkedin.com", "http://www.google.com.br",
			"http://www.list.tmall.com", "http://www.google.fr", "http://www.google.ru", "http://www.yandex.ru", "http://www.google.com.hk", "http://www.netflix.com",
			"http://www.yahoo.co.jp", "http://www.google.it", "http://www.t.co", "http://www.ebay.com", "http://www.imgur.com", "http://www.google.es", "http://www.pornhub.com",
			"http://www.bing.com", "http://www.msn.com", "http://www.onclkds.com", "http://www.google.ca", "http://www.twitch.tv", "http://www.google.com.mx",
			"http://www.livejasmin.com", "http://www.tumblr.com", "http://www.alipay.com", "http://www.hao123.com", "http://www.mail.ru", "http://www.microsoft.com",
			"http://www.aliexpress.com", "http://www.wordpress.com", "http://www.ok.ru", "http://www.xvideos.com", "http://www.stackoverflow.com", "http://www.imdb.com",
			"http://www.blogspot.com", "http://www.amazon.co.jp", "http://www.github.com", "http://www.pinterest.com", "http://www.office.com", "http://www.apple.com",
			"http://www.google.com.tr", "http://www.csdn.net", "http://www.wikia.com", "http://www.popads.net", "http://www.microsoftonline.com", "http://www.youth.cn",
			"http://www.google.com.au", "http://www.google.com.tw", "http://www.whatsapp.com", "http://www.paypal.com", "http://www.diply.com", "http://www.google.pl",
			"http://www.xhamster.com", "http://www.detail.tmall.com", "http://www.google.co.id", "http://www.adobe.com", "http://www.bongacams.com", "http://www.coccoc.com",
			"http://www.gmw.cn", "http://www.soso.com", "http://www.bbc.co.uk", "http://www.dropbox.com", "http://www.googleusercontent.com", "http://www.amazon.de",
			"http://www.pixnet.net", "http://www.craigslist.org", "http://www.google.com.pk", "http://www.txxx.com", "http://www.google.co.th", "http://www.google.com.ar",
			"http://www.thepiratebay.org", "http://www.bbc.com", "http://www.google.com.eg", "http://www.tianya.cn", "http://www.cnn.com", "http://www.amazon.in",
			"http://www.so.com", "http://www.google.com.sa", "http://www.booking.com", "http://www.porn555.com", "http://www.china.com", "http://www.fc2.com",
			"http://www.quora.com", "http://www.clicksgear.com", "http://www.amazon.co.uk", "http://www.soundcloud.com", "http://www.uptodown.com", "http://www.google.com.ua",
			"http://www.naver.com", "http://www.nicovideo.jp", "http://www.google.nl", "http://www.ask.com", "http://www.savefrom.net", "http://www.rakuten.co.jp",
			"http://www.nytimes.com", "http://www.amazonaws.com", "http://www.dailymotion.com", "http://www.ettoday.net", "http://www.xnxx.com", "http://www.theguardian.com",
			"http://www.blastingnews.com", "http://www.adf.ly", "http://www.google.co.ve", "http://www.google.co.za", "http://www.espn.com", "http://www.detik.com",
			"http://www.fbcdn.net", "http://www.onlinesbi.com", "http://www.ebay.de", "http://www.tribunnews.com", "http://www.blogger.com", "http://www.vice.com",
			"http://www.stackexchange.com", "http://www.salesforce.com", "http://www.vimeo.com", "http://www.google.co.kr", "http://www.chase.com", "http://www.steamcommunity.com",
			"http://www.chaturbate.com", "http://www.ebay.co.uk", "http://www.ladbible.com", "http://www.spotify.com", "http://www.gomovies.to", "http://www.google.gr",
			"http://www.google.com.vn", "http://www.dailymail.co.uk", "http://www.buzzfeed.com", "http://www.mozilla.org", "http://www.globo.com", "http://www.ntd.tv",
			"http://www.google.com.sg", "http://www.xinhuanet.com", "http://www.cnet.com", "http://www.google.com.co", "http://www.slideshare.net", "http://www.google.be",
			"http://www.avito.ru", "http://www.mediafire.com", "http://www.openload.co", "http://www.upornia.com", "http://www.google.se", "http://www.popcash.net",
			"http://www.indeed.com", "http://www.flipkart.com", "http://www.google.com.ph", "http://www.daikynguyenvn.com", "http://www.douyu.com", "http://www.deviantart.com",
			"http://www.uol.com.br", "http://www.github.io", "http://www.google.az", "http://www.twimg.com", "http://www.rambler.ru", "http://www.wikihow.com",
			"http://www.washingtonpost.com", "http://www.google.cn", "http://www.roblox.com", "http://www.thewhizmarketing.com", "http://www.pinimg.com", "http://www.bet365.com",
			"http://www.nih.gov", "http://www.w3schools.com", "http://www.force.com", "http://www.google.at", "http://www.steampowered.com", "http://www.9gag.com",
			"http://www.sogou.com", "http://www.etsy.com", "http://www.yelp.com", "http://www.godaddy.com", "http://www.google.com.ng", "http://www.softonic.com",
			"http://www.iwanttodeliver.com", "http://www.hclips.com", "http://www.google.com.pe", "http://www.walmart.com", "http://www.redtube.com", "http://www.zhihu.com",
			"http://www.performanceadexchange.com", "http://www.tokopedia.com", "http://www.alibaba.com", "http://www.slack.com", "http://www.redd.it", "http://www.4chan.org",
			"http://www.babytree.com", "http://www.google.cz", "http://www.trackmedia101.com", "http://www.messenger.com", "http://www.mercadolivre.com.br", "http://www.myway.com",
			"http://www.google.ro", "http://www.gfycat.com", "http://www.china.com.cn", "http://www.google.ch", "http://www.bp.blogspot.com", "http://www.bankofamerica.com",
			"http://www.google.cl", "http://www.hotstar.com", "http://www.metropcs.mobi", "http://www.rarbg.to", "http://www.google.no", "http://www.askcom.me",
			"http://www.indiatimes.com", "http://www.cpm10.com", "http://www.google.pt", "http://www.amazon.fr", "http://www.tripadvisor.com", "http://www.1688.com",
			"http://www.zillow.com", "http://www.abs-cbn.com", "http://www.trello.com", "http://www.mama.cn", "http://www.kinogo.club", "http://www.weather.com",
			"http://www.discordapp.com", "http://www.google.ae", "http://www.outbrain.com", "http://www.wellsfargo.com", "http://www.amazon.it", "http://www.huffingtonpost.com",
			"http://www.reimageplus.com", "http://www.forbes.com", "http://www.irctc.co.in", "http://www.hotmovs.com", "http://www.bilibili.com", "http://www.yts.ag",
			"http://www.people.com.cn", "http://www.ameblo.jp", "http://www.google.co.ao", "http://www.dingit.tv", "http://www.youporn.com", "http://www.mega.nz",
			"http://www.google.dz", "http://www.livejournal.com", "http://www.39.net", "http://www.gamepedia.com", "http://www.espncricinfo.com", "http://www.youm7.com",
			"http://www.ign.com", "http://www.battle.net", "http://www.speedtest.net", "http://www.adexchangeprediction.com", "http://www.spotscenered.info",
			"http://www.google.ie", "http://www.liputan6.com", "http://www.google.hu", "http://www.ltn.com.tw", "http://www.files.wordpress.com", "http://www.ikea.com",
			"http://www.wetransfer.com", "http://www.wordreference.com", "http://www.kompas.com", "http://www.sharepoint.com", "http://www.doubleclick.net",
			"http://www.cnblogs.com", "http://www.bitauto.com", "http://www.kissanime.ru", "http://www.google.co.il", "http://www.wikimedia.org", "http://www.aol.com",
			"http://www.huaban.com", "http://www.torrentz2.eu", "http://www.foxnews.com", "http://www.google.dk", "http://www.allegro.pl", "http://www.archive.org",
			"http://www.freepik.com", "http://www.cricbuzz.com", "http://www.feedly.com", "http://www.breitbart.com", "http://www.google.fi", "http://www.leboncoin.fr",
			"http://www.shutterstock.com", "http://www.kakaku.com", "http://www.giphy.com", "http://www.ebay-kleinanzeigen.de", "http://www.telegraph.co.uk",
			"http://www.bestbuy.com", "http://www.businessinsider.com", "http://www.sabah.com.tr", "http://www.newstarads.com", "http://www.varzesh3.com", "http://www.skype.com",
			"http://www.kinopoisk.ru", "http://www.daum.net", "http://www.rutracker.org", "http://www.streamable.com", "http://www.blogspot.com.br", "http://www.thesaurus.com",
			"http://www.airbnb.com", "http://www.tfetimes.com", "http://www.huanqiu.com", "http://www.caijing.com.cn", "http://www.scribd.com", "http://www.k618.cn",
			"http://www.onlinevideoconverter.com", "http://www.bukalapak.com", "http://www.mediawhirl.net", "http://www.sberbank.ru", "http://www.flickr.com",
			"http://www.sourceforge.net", "http://www.weebly.com", "http://www.genius.com", "http://www.subject.tmall.com", "http://www.amazon.cn", "http://www.zippyshare.com",
			"http://www.researchgate.net", "http://www.gismeteo.ru", "http://www.chinadaily.com.cn", "http://www.spankbang.com", "http://www.amazon.es",
			"http://www.codeonclick.com", "http://www.wittyfeed.com", "http://www.hola.com", "http://www.ouo.io", "http://www.xfinity.com", "http://www.taringa.net",
			"http://www.web.de", "http://www.mmofreegames.online", "http://www.blogspot.in", "http://www.asos.com", "http://www.nownews.com", "http://www.youtube-mp3.org",
			"http://www.google.sk", "http://www.rumble.com", "http://www.telegram.org", "http://www.independent.co.uk", "http://www.naver.jp", "http://www.gmx.net",
			"http://www.homedepot.com", "http://www.gamefaqs.com", "http://www.media.tumblr.com", "http://www.videodownloadconverter.com", "http://www.aliyun.com",
			"http://www.accuweather.com", "http://www.1337x.to", "http://www.ndtv.com", "http://www.goo.ne.jp", "http://www.mailchimp.com", "http://www.userapi.com",
			"http://www.rt.com", "http://www.kaskus.co.id", "http://www.oracle.com", "http://www.digikala.com", "http://www.2ch.net", "http://www.conservativetribune.com",
			"http://www.orange.fr", "http://www.gearbest.com", "http://www.hatena.ne.jp", "http://www.weevah2.top", "http://www.wordpress.org", "http://www.providr.com",
			"http://www.shopify.com", "http://www.eastday.com", "http://www.medium.com", "http://www.goodreads.com", "http://www.hatenablog.com", "http://www.redirectvoluum.com",
			"http://www.lifebuzz.com", "http://www.bet9ja.com", "http://www.livedoor.jp", "http://www.zendesk.com", "http://www.icloud.com", "http://www.samsung.com",
			"http://www.amazon.ca", "http://www.appspot.com", "http://www.google.kz", "http://www.onet.pl", "http://www.aparat.com", "http://www.hulu.com",
			"http://www.repubblica.it", "http://www.olx.ua", "http://www.cnzz.com", "http://www.elpais.com", "http://www.hp.com", "http://www.yesky.com", "http://www.subscene.com",
			"http://www.target.com", "http://www.taboola.com", "http://www.go.com", "http://www.ci123.com", "http://www.evernote.com", "http://www.leagueoflegends.com",
			"http://www.rottentomatoes.com", "http://www.ensonhaber.com", "http://www.capitalone.com", "http://www.beeg.com", "http://www.youdao.com",
			"http://www.americanexpress.com", "http://www.usps.com", "http://www.reverso.net", "http://www.spiegel.de", "http://www.naij.com", "http://www.canva.com",
			"http://www.taleo.net", "http://www.hdfcbank.com", "http://www.doublepimpssl.com", "http://www.atlassian.net", "http://www.mercadolibre.com.ar", "http://www.gyazo.com",
			"http://www.pandora.com", "http://www.rednet.cn", "http://www.haber7.com", "http://www.perfecttoolmedia.com", "http://www.onedio.com", "http://www.udemy.com",
			"http://www.seasonvar.ru", "http://www.livedoor.com", "http://www.wp.pl", "http://www.baike.com", "http://www.ups.com", "http://www.google.com.kw",
			"http://www.theverge.com", "http://www.marca.com", "http://www.qiita.com", "http://www.urbandictionary.com", "http://www.exoclick.com", "http://www.duckduckgo.com",
			"http://www.sciencedirect.com", "http://www.sumatoad.com", "http://www.themeforest.net", "http://www.thewhizproducts.com", "http://www.fiverr.com",
			"http://www.ultimate-guitar.com", "http://www.shink.in", "http://www.box.com", "http://www.mlb.com", "http://www.behance.net", "http://www.iqiyi.com",
			"http://www.upwork.com", "http://www.merdeka.com", "http://www.line.me", "http://www.launchpage.org", "http://www.setn.com", "http://www.ebay.it",
			"http://www.bloomberg.com", "http://www.ibm.com", "http://www.cloudfront.net", "http://www.google.co.nz", "http://www.patreon.com", "http://www.piz7ohhujogi.com",
			"http://www.kickstarter.com", "http://www.boredpanda.com", "http://www.sportbible.com", "http://www.wix.com", "http://www.rediff.com", "http://www.dell.com",
			"http://www.mi.com", "http://www.google.bg", "http://www.free.fr", "http://www.cerpen.co.id", "http://www.blackboard.com", "http://www.ytimg.com",
			"http://www.weblio.jp", "http://www.intuit.com", "http://www.reuters.com", "http://www.4dsply.com", "http://www.chatwork.com", "http://www.doublepimp.com",
			"http://www.momoshop.com.tw", "http://www.seznam.cz", "http://www.groupon.com", "http://www.mit.edu", "http://www.goal.com", "http://www.biobiochile.cl",
			"http://www.tutorialspoint.com", "http://www.camdolls.com", "http://www.playstation.com", "http://www.mbc.net", "http://www.office365.com",
			"http://www.givemesport.com", "http://www.poloniex.com", "http://www.scribol.com", "http://www.gizmodo.com", "http://www.icicibank.com", "http://www.dictionary.com",
			"http://www.paytm.com", "http://www.vtv.vn", "http://www.webtretho.com", "http://www.fedex.com", "http://www.glassdoor.com", "http://www.slickdeals.net",
			"http://www.patch.com", "http://www.t-online.de", "http://www.wattpad.com", "http://www.163.com", "http://www.myanimelist.net", "http://www.webmd.com",
			"http://www.ck101.com", "http://www.hespress.com", "http://www.humblebundle.com", "http://www.naukri.com", "http://www.nur.kz", "http://www.zoho.com",
			"http://www.coinmarketcap.com", "http://www.pantip.com", "http://www.mercadolibre.com.mx", "http://www.azlyrics.com", "http://www.flirt4free.com",
			"http://www.umblr.com", "http://www.usatoday.com", "http://www.iqoption.com", "http://www.pixabay.com", "http://www.citi.com", "http://www.lazada.co.id",
			"http://www.libero.it", "http://www.gamer.com.tw", "http://www.pulseonclick.com", "http://www.sahibinden.com", "http://www.kapanlagi.com", "http://www.google.lk",
			"http://www.coinbase.com", "http://www.frstlead.com", "http://www.wiktionary.org", "http://www.ebay.com.au", "http://www.gsmarena.com", "http://www.filehippo.com",
			"http://www.prezi.com", "http://www.tube8.com", "http://www.google.rs", "http://www.uidai.gov.in", "http://www.lemonde.fr", "http://www.blogspot.mx",
			"http://www.nametests.com", "http://www.newtabtv.com", "http://www.billdesk.com", "http://www.pikabu.ru", "http://www.okdiario.com", "http://www.jrj.com.cn",
			"http://www.list-manage.com", "http://www.manoramaonline.com", "http://www.yandex.ua", "http://www.shaparak.ir", "http://www.uploaded.net",
			"http://www.siteadvisor.com", "http://www.albawabhnews.com", "http://www.wsj.com", "http://www.tistory.com", "http://www.hilltopads.net", "http://www.vporn.com",
			"http://www.wiley.com", "http://www.google.by", "http://www.tvbs.com.tw", "http://www.kooora.com", "http://www.xda-developers.com", "http://www.wixsite.com",
			"http://www.engadget.com", "http://www.oeeee.com", "http://www.nike.com", "http://www.expedia.com", "http://www.springer.com", "http://www.friv.com",
			"http://www.elmundo.es", "http://www.bild.de", "http://www.tabelog.com", "http://www.hurriyet.com.tr", "http://www.pages.tmall.com", "http://www.thefreedictionary.com",
			"http://www.sabq.org", "http://www.google.com.do", "http://www.ptt.cc", "http://www.wowhead.com", "http://www.olx.pl", "http://www.grid.id", "http://www.emol.com",
			"http://www.nba.com", "http://www.drom.ru", "http://www.terraclicks.com", "http://www.hm.com", "http://www.bleacherreport.com", "http://www.inquirer.net",
			"http://www.instructure.com", "http://www.re19fla.com", "http://www.npr.org", "http://www.chip.de", "http://www.fmovies.se", "http://www.cambridge.org",
			"http://www.asana.com", "http://www.academia.edu", "http://www.my-hit.org", "http://www.att.com", "http://www.kijiji.ca", "http://www.hubspot.com", "http://www.as.com",
			"http://www.avg.com", "http://www.4shared.com", "http://www.telewebion.com", "http://www.olx.com.br", "http://www.asus.com", "http://www.mirror.co.uk",
			"http://www.17ok.com", "http://www.souq.com", "http://www.youjizz.com", "http://www.discogs.com", "http://www.mywatchseries.to", "http://www.hotels.com",
			"http://www.getpocket.com", "http://www.milliyet.com.tr", "http://www.ctitv.com.tw", "http://www.paclitor.com", "http://www.blogfa.com", "http://www.buyma.com",
			"http://www.gamespot.com", "http://www.104.com.tw", "http://www.newegg.com", "http://www.wish.com", "http://www.techcrunch.com", "http://www.hamariweb.com",
			"http://www.prothom-alo.com", "http://www.surveymonkey.com", "http://www.ria.ru", "http://www.bandcamp.com", "http://www.okta.com", "http://www.nikkei.com",
			"http://www.yadi.sk", "http://www.google.hr", "http://www.dmm.co.jp", "http://www.x48fly.com", "http://www.corriere.it", "http://www.drtuber.com",
			"http://www.comcast.net", "http://www.wunderground.com", "http://www.imwhite.ru", "http://www.squarespace.com", "http://www.xe.com", "http://www.neobux.com",
			"http://www.investopedia.com", "http://www.banggood.com", "http://www.animeflv.net", "http://www.moneycontrol.com", "http://www.convert2mp3.net",
			"http://www.reallifecam.com", "http://www.fbsbx.com", "http://www.norton.com", "http://www.discuss.com.hk", "http://www.thekitchn.com", "http://www.ask.fm",
			"http://www.google.com.ly", "http://www.ebay.in", "http://www.life.tw", "http://www.badoo.com", "http://www.beytoote.com", "http://www.drive2.ru",
			"http://www.eksisozluk.com", "http://www.adp.com", "http://www.birdieulx.com", "http://www.suning.com", "http://www.ouedkniss.com", "http://www.douban.com",
			"http://www.gogoanime.io", "http://www.namnak.com", "http://www.kotaku.com", "http://www.mercadolibre.com.ve", "http://www.liftable.com", "http://www.okcupid.com",
			"http://www.myfreecams.com", "http://www.liveadexchanger.com", "http://www.bitbucket.org", "http://www.appledaily.com.tw", "http://www.chaoshi.tmall.com",
			"http://www.japanpost.jp", "http://www.youboy.com", "http://www.solarmoviez.to", "http://www.elbalad.news", "http://www.porn.com", "http://www.webex.com",
			"http://www.lifehacker.com", "http://www.meetup.com", "http://www.sex.com", "http://www.southwest.com", "http://www.goo.gl", "http://www.linkshrink.net",
			"http://www.hdzog.com", "http://www.translationbuddy.com", "http://www.khanacademy.org", "http://www.googlevideo.com", "http://www.verizonwireless.com",
			"http://www.nanoadexchange.com", "http://www.google.tn", "http://www.lefigaro.fr", "http://www.mysagagame.com", "http://www.51sole.com", "http://www.chinaz.com",
			"http://www.streamcloud.eu", "http://www.directrev.com", "http://www.yenisafak.com", "http://www.jeuxvideo.com", "http://www.lapatilla.com",
			"http://www.motherless.com", "http://www.westernjournalism.com", "http://www.g2a.com", "http://www.drudgereport.com", "http://www.lenta.ru", "http://www.uptobox.com",
			"http://www.viva.co.id", "http://www.dafont.com", "http://www.ccm.net", "http://www.content1req.com", "http://www.rapidgator.net",
			"http://www.adnetworkperformance.com", "http://www.coursera.org", "http://www.thevideo.me", "http://www.realtor.com", "http://www.www.gov.uk", "http://www.lowes.com",
			"http://www.nordstrom.com", "http://www.thesun.co.uk", "http://www.alicdn.com", "http://www.superuser.com", "http://www.jianshu.com", "http://www.brilio.net",
			"http://www.ecosia.org", "http://www.watchfree.to", "http://www.voyeurhit.com", "http://www.mobile.de", "http://www.mediaoffers.click", "http://www.caliente.mx",
			"http://www.sakura.ne.jp", "http://www.cnbc.com", "http://www.gmarket.co.kr", "http://www.subito.it", "http://www.prestoris.com", "http://www.macys.com",
			"http://www.lenovo.com", "http://www.bitly.com", "http://www.infusionsoft.com", "http://www.voc.com.cn", "http://www.mundo.com", "http://www.autodesk.com",
			"http://www.op.gg", "http://www.udn.com", "http://www.okezone.com", "http://www.android.com", "http://www.crunchyroll.com", "http://www.zone-telechargement.ws",
			"http://www.popmyads.com", "http://www.discover.com", "http://www.urdupoint.com", "http://www.plarium.com", "http://www.bodybuilding.com", "http://www.jabong.com",
			"http://www.eventbrite.com", "http://www.xgames-04.com", "http://www.vnexpress.net", "http://www.kayak.com", "http://www.addthis.com", "http://www.chinaso.com",
			"http://www.secureserver.net", "http://www.commentcamarche.net", "http://www.ca.gov", "http://www.google.com.ec", "http://www.uzone.id", "http://www.fanfiction.net",
			"http://www.nypost.com", "http://www.europa.eu", "http://www.kinokrad.co", "http://www.kissasian.com", "http://www.thebalance.com", "http://www.express.co.uk",
			"http://www.stockstar.com", "http://www.eskimi.com", "http://www.dailypakistan.com.pk", "http://www.divar.ir", "http://www.stanford.edu", "http://www.likemag.com",
			"http://www.timeanddate.com", "http://www.howtogeek.com", "http://www.wp.com", "http://www.ipetgroup.com", "http://www.disq.us", "http://www.duolingo.com",
			"http://www.quizlet.com", "http://www.trulia.com", "http://www.fatosdesconhecidos.com.br", "http://www.jimdo.com", "http://www.apple-kungfu.com", "http://www.4pda.ru",
			"http://www.investing.com", "http://www.state.gov", "http://www.unity3d.com", "http://www.snapdeal.com", "http://www.intoday.in", "http://www.google.lt",
			"http://www.indianexpress.com", "http://www.gotporn.com", "http://www.torrentproject.se", "http://www.cisco.com", "http://www.uber.com", "http://www.zing.vn",
			"http://www.intel.com", "http://www.google.iq", "http://www.politico.com", "http://www.php.net", "http://www.ebay.fr", "http://www.kinoprofi.org",
			"http://www.interia.pl", "http://www.nikkeibp.co.jp", "http://www.nextlnk13.com", "http://www.instructables.com", "http://www.mobile01.com", "http://www.xtube.com",
			"http://www.tomshardware.com", "http://www.fanpage.gr", "http://www.cdiscount.com", "http://www.gamingwonderland.com", "http://www.makemytrip.com",
			"http://www.latimes.com", "http://www.y8.com", "http://www.nbcnews.com", "http://www.pchome.com.tw", "http://www.kizlarsoruyor.com", "http://www.theepochtimes.com",
			"http://www.seesaa.net", "http://www.gazetaexpress.com", "http://www.thehill.com", "http://www.disqus.com", "http://www.sporx.com", "http://www.faithtap.com",
			"http://www.itmedia.co.jp", "http://www.blpmovies.com", "http://www.lifewire.com", "http://www.mangafox.me", "http://www.grammarly.com", "http://www.fidelity.com",
			"http://www.tebyan.net", "http://www.elfagr.org", "http://www.el-nacional.com", "http://www.issuu.com", "http://www.jw.org", "http://www.donga.com",
			"http://www.techradar.com", "http://www.hootsuite.com", "http://www.oschina.net", "http://www.deviantart.net", "http://www.prnt.sc", "http://www.ieee.org",
			"http://www.zhanqi.tv", "http://www.rbc.ru", "http://www.cam4.com", "http://www.merriam-webster.com", "http://www.rutube.ru", "http://www.google.com.mm",
			"http://www.cpmofferconvert.com", "http://www.piriform.com", "http://www.58.com", "http://www.banvenez.com", "http://www.blogspot.jp", "http://www.eyny.com",
			"http://www.bhphotovideo.com", "http://www.theatlantic.com", "http://www.comicbook.com", "http://www.pirateproxy.cc", "http://www.sh.st", "http://www.vetogate.com",
			"http://www.time.com", "http://www.sapo.pt", "http://www.lazada.com.ph", "http://www.gazeta.pl", "http://www.google.com.gt", "http://www.ukr.net",
			"http://www.nature.com", "http://www.justdial.com", "http://www.olx.in", "http://www.chouftv.ma", "http://www.gongchang.com", "http://www.yaplakal.com",
			"http://www.myfitnesspal.com", "http://www.python.org", "http://www.primewire.ag", "http://www.gazzetta.it", "http://www.dict.cc", "http://www.allrecipes.com",
			"http://www.asahi.com", "http://www.qoolquiz.com", "http://www.airtel.in", "http://www.andhrajyothy.com", "http://www.52pk.com", "http://www.chron.com",
			"http://www.alsbbora.com", "http://www.cqnews.net", "http://www.sarkariresult.com", "http://www.java.com", "http://www.farsnews.com", "http://www.pof.com",
			"http://www.delta.com", "http://www.admarketplace.net", "http://www.nhk.or.jp", "http://www.codepen.io", "http://www.wykop.pl", "http://www.mashable.com",
			"http://www.askubuntu.com", "http://www.azxsd.pro", "http://www.cbc.ca", "http://www.idnes.cz", "http://www.yjc.ir", "http://www.sinoptik.ua",
			"http://www.absoluteclickscom.com", "http://www.bookmyshow.com", "http://www.gutefrage.net", "http://www.allocine.fr", "http://www.sputniknews.com",
			"http://www.almasryalyoum.com", "http://www.yandex.com.tr", "http://www.bhaskar.com", "http://www.bankmellat.ir", "http://www.mynavi.jp", "http://www.turbobit.net",
			"http://www.google.si", "http://www.strava.com", "http://www.ruten.com.tw", "http://www.dream.co.id", "http://www.livescore.com", "http://www.clipconverter.cc",
			"http://www.nocookie.net", "http://www.elvenar.com", "http://www.lk21.me", "http://www.blog.me", "http://www.xbox.com", "http://www.vidzi.tv",
			"http://www.lazada.com.my", "http://www.thepennyhoarder.com", "http://www.liveinternet.ru", "http://www.freejobalert.com", "http://www.familydoctor.com.cn",
			"http://www.teepr.com", "http://www.brazzers.com", "http://www.prpops.com", "http://www.world.tmall.com", "http://www.liveleak.com", "http://www.wtoip.com",
			"http://www.ticketmaster.com", "http://www.bomb01.com", "http://www.caixa.gov.br", "http://www.junbi-tracker.com", "http://www.visualstudio.com",
			"http://www.usnews.com", "http://www.ampxchange.com", "http://www.fromdoctopdf.com", "http://www.tamilrockers.lv", "http://www.zomato.com", "http://www.suara.com",
			"http://www.11st.co.kr", "http://www.google.tm", "http://www.blog.jp", "http://www.bintang.com", "http://www.metropoles.com", "http://www.wuxiaworld.com",
			"http://www.videoyoum7.com", "http://www.ea.com", "http://www.opensubtitles.org", "http://www.cbsnews.com", "http://www.redfin.com", "http://www.perfectgirls.net",
			"http://www.internetdownloadmanager.com", "http://www.ted.com", "http://www.nasa.gov", "http://www.food.tmall.com", "http://www.aljazeera.net", "http://www.lun.com",
			"http://www.searchprivate.org", "http://www.agoda.com", "http://www.livestrong.com", "http://www.inven.co.kr", "http://www.labanquepostale.fr",
			"http://www.njoyapps.com", "http://www.lazada.co.th", "http://www.meb.gov.tr", "http://www.qingdaonews.com", "http://www.zoom.us", "http://www.alodokter.com",
			"http://www.focus.de", "http://www.href.li", "http://www.wired.com", "http://www.yandex.kz", "http://www.welt.de", "http://www.dmv.org", "http://www.dcard.tw");
	
}
