module XR3Player {
	exports com.goxr3plus.xr3player.services.chromium;
	exports com.goxr3plus.xr3player.controllers.moviemode;
	exports com.goxr3plus.xr3player.controllers.smartcontroller;
	exports com.goxr3plus.xr3player.models.xplayer;
	exports com.goxr3plus.xr3player.services.systemtree;
	exports com.goxr3plus.xr3player.controllers.dropbox;
	exports com.goxr3plus.xr3player.xplayer.visualizer.core;
	exports com.goxr3plus.xr3player.controllers.loginmode;
	exports com.goxr3plus.xr3player.services.dropbox;
	exports com.goxr3plus.xr3player.utils.general;
	exports com.goxr3plus.xr3player.controllers.tagging;
	exports com.goxr3plus.xr3player.models.smartcontroller;
	exports com.goxr3plus.xr3player.utils.io;
	exports com.goxr3plus.xr3player.xplayer.waveform;
	exports com.goxr3plus.xr3player.services.database;
	exports com.goxr3plus.xr3player.services.xplayer;
	exports com.goxr3plus.xr3player.controllers.custom;
	exports com.goxr3plus.xr3player.controllers.general;
	exports com.goxr3plus.xr3player.database;
	exports com.goxr3plus.xr3player.services.loginmode;
	exports com.goxr3plus.xr3player.xplayer.visualizer.geometry;
	exports com.goxr3plus.xr3player.enums;
	exports com.goxr3plus.xr3player.controllers.chromium;
	exports com.goxr3plus.xr3player.controllers.settings;
	exports com.goxr3plus.xr3player.services.smartcontroller;
	exports com.goxr3plus.xr3player.controllers.librarymode;
	exports com.goxr3plus.xr3player.controllers.systemtree;
	exports com.goxr3plus.xr3player.controllers.windows;
	exports com.goxr3plus.xr3player.xplayer.dsp;
	exports com.goxr3plus.xr3player.application;
	exports com.goxr3plus.xr3player.xplayer.microphone;
	exports com.goxr3plus.xr3player.utils.javafx;
	exports com.goxr3plus.xr3player.controllers.djmode;
	exports com.goxr3plus.xr3player.services.zipping;
	exports com.goxr3plus.xr3player.controllers.xplayer;
	exports com.goxr3plus.xr3player.xplayer.visualizer.presenter;
	exports com.goxr3plus.xr3player.services.general;
	exports com.goxr3plus.xr3player.models.lists;

	opens com.goxr3plus.xr3player.controllers.general to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.windows to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.tagging to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.settings to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.custom to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.systemtree to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.smartcontroller to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.moviemode to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.xplayer to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.djmode to javafx.fxml;
	opens com.goxr3plus.xr3player.xplayer.visualizer.presenter to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.librarymode to javafx.fxml;
	opens com.goxr3plus.xr3player.controllers.loginmode to javafx.fxml;
//	opens java.lang.reflect to XR3Player;





	requires java.sql;
	requires java.logging;
	requires FX.BorderlessScene;
//    requires XR3Capture;
	requires com.goxr3plus.streamplayer;
	requires com.jfoenix;
	requires commons.validator;
	requires controlsfx;
	requires dropbox.core.sdk;
	requires evo.inflector;
	requires flowless;
	requires image4j;
	requires jaudiotagger;
	requires java.flac.encoder;
	requires java.google.speech.api;
	requires javafx.base;
	requires javafx.controls;
	requires javafx.fxml;
	requires javafx.graphics;
	requires javafx.media;
	requires javafx.swing;
	requires javasysmon2;
	requires jave.core;
	requires jnativehook;
	requires json;
	requires jxbrowser;
	requires mp3agic;
	requires org.apache.commons.io;
	requires org.jsoup;
	requires org.kordamp.iconli.core;
	requires org.kordamp.ikonli.javafx;
	requires reactfx;
	requires richtextfx;
	requires zt.zip;
}